#include <fltKernel.h>
#define YOMF_EVENT_ABI 2u
#define YOMF_VOLUME_NAME_CHARS 64u
typedef struct _YOMF_EVENT { ULONG Size; ULONG AbiVersion; ULONGLONG Sequence; LONGLONG SystemTime100ns; ULONG ProcessId; UCHAR MajorFunction; UCHAR RequestorMode; USHORT Reserved; ULONG IrpFlags; WCHAR VolumeName[YOMF_VOLUME_NAME_CHARS]; } YOMF_EVENT;
typedef struct _YOMF_INSTANCE_CONTEXT { WCHAR VolumeName[YOMF_VOLUME_NAME_CHARS]; } YOMF_INSTANCE_CONTEXT,*PYOMF_INSTANCE_CONTEXT;
PFLT_FILTER g_Filter=NULL; PFLT_PORT g_ServerPort=NULL; PFLT_PORT g_ClientPort=NULL; volatile LONG64 g_Sequence=0;
DRIVER_INITIALIZE DriverEntry;
NTSTATUS YomfUnload(FLT_FILTER_UNLOAD_FLAGS flags);
NTSTATUS YomfInstanceSetup(PCFLT_RELATED_OBJECTS objects,FLT_INSTANCE_SETUP_FLAGS flags,DEVICE_TYPE volumeDeviceType,FLT_FILESYSTEM_TYPE fileSystemType);
FLT_PREOP_CALLBACK_STATUS YomfPreOperation(PFLT_CALLBACK_DATA data,PCFLT_RELATED_OBJECTS objects,PVOID* completionContext);
VOID YomfContextCleanup(PFLT_CONTEXT context,FLT_CONTEXT_TYPE contextType){UNREFERENCED_PARAMETER(context);UNREFERENCED_PARAMETER(contextType);}
NTSTATUS YomfConnect(PFLT_PORT clientPort,PVOID serverPortCookie,PVOID connectionContext,ULONG sizeOfContext,PVOID* connectionCookie){UNREFERENCED_PARAMETER(serverPortCookie);UNREFERENCED_PARAMETER(connectionContext);UNREFERENCED_PARAMETER(sizeOfContext);UNREFERENCED_PARAMETER(connectionCookie);return InterlockedCompareExchangePointer((PVOID volatile*)&g_ClientPort,clientPort,NULL)==NULL?STATUS_SUCCESS:STATUS_DEVICE_BUSY;}
VOID YomfDisconnect(PVOID connectionCookie){PFLT_PORT port;UNREFERENCED_PARAMETER(connectionCookie);port=(PFLT_PORT)InterlockedExchangePointer((PVOID volatile*)&g_ClientPort,NULL);if(port!=NULL)FltCloseClientPort(g_Filter,&port);}
static const FLT_OPERATION_REGISTRATION g_Callbacks[]={{IRP_MJ_CREATE,0,YomfPreOperation,NULL},{IRP_MJ_READ,0,YomfPreOperation,NULL},{IRP_MJ_WRITE,0,YomfPreOperation,NULL},{IRP_MJ_SET_INFORMATION,0,YomfPreOperation,NULL},{IRP_MJ_ACQUIRE_FOR_SECTION_SYNCHRONIZATION,0,YomfPreOperation,NULL},{IRP_MJ_OPERATION_END}};
static const FLT_CONTEXT_REGISTRATION g_Contexts[]={{FLT_INSTANCE_CONTEXT,0,YomfContextCleanup,sizeof(YOMF_INSTANCE_CONTEXT),'cMoY',NULL,NULL,NULL},{FLT_CONTEXT_END}};
static const FLT_REGISTRATION g_Registration={sizeof(FLT_REGISTRATION),FLT_REGISTRATION_VERSION,0,g_Contexts,g_Callbacks,YomfUnload,YomfInstanceSetup,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL};
NTSTATUS DriverEntry(PDRIVER_OBJECT driverObject,PUNICODE_STRING registryPath){NTSTATUS status;PSECURITY_DESCRIPTOR sd=NULL;OBJECT_ATTRIBUTES oa;UNICODE_STRING name=RTL_CONSTANT_STRING(L"\\YoungOneMediaFilterPort");UNREFERENCED_PARAMETER(registryPath);status=FltRegisterFilter(driverObject,&g_Registration,&g_Filter);if(!NT_SUCCESS(status))return status;status=FltBuildDefaultSecurityDescriptor(&sd,FLT_PORT_ALL_ACCESS);if(!NT_SUCCESS(status))goto Fail;InitializeObjectAttributes(&oa,&name,OBJ_KERNEL_HANDLE|OBJ_CASE_INSENSITIVE,NULL,sd);status=FltCreateCommunicationPort(g_Filter,&g_ServerPort,&oa,NULL,YomfConnect,YomfDisconnect,NULL,1);FltFreeSecurityDescriptor(sd);sd=NULL;if(!NT_SUCCESS(status))goto Fail;status=FltStartFiltering(g_Filter);if(NT_SUCCESS(status))return status;Fail:if(sd!=NULL)FltFreeSecurityDescriptor(sd);if(g_ServerPort!=NULL){FltCloseCommunicationPort(g_ServerPort);g_ServerPort=NULL;}FltUnregisterFilter(g_Filter);g_Filter=NULL;return status;}
NTSTATUS YomfUnload(FLT_FILTER_UNLOAD_FLAGS flags){PFLT_PORT client;UNREFERENCED_PARAMETER(flags);client=(PFLT_PORT)InterlockedExchangePointer((PVOID volatile*)&g_ClientPort,NULL);if(client!=NULL)FltCloseClientPort(g_Filter,&client);if(g_ServerPort!=NULL){FltCloseCommunicationPort(g_ServerPort);g_ServerPort=NULL;}if(g_Filter!=NULL){FltUnregisterFilter(g_Filter);g_Filter=NULL;}return STATUS_SUCCESS;}
NTSTATUS YomfInstanceSetup(PCFLT_RELATED_OBJECTS objects,FLT_INSTANCE_SETUP_FLAGS flags,DEVICE_TYPE volumeDeviceType,FLT_FILESYSTEM_TYPE fileSystemType){ULONG needed=0;NTSTATUS status;BOOLEAN removable;PFLT_VOLUME_PROPERTIES properties;PYOMF_INSTANCE_CONTEXT context=NULL;UNICODE_STRING volumeName;UNREFERENCED_PARAMETER(flags);UNREFERENCED_PARAMETER(fileSystemType);if(volumeDeviceType!=FILE_DEVICE_DISK_FILE_SYSTEM)return STATUS_FLT_DO_NOT_ATTACH;status=FltGetVolumeProperties(objects->Volume,NULL,0,&needed);if(status!=STATUS_BUFFER_TOO_SMALL||needed<sizeof(FLT_VOLUME_PROPERTIES))return STATUS_FLT_DO_NOT_ATTACH;properties=(PFLT_VOLUME_PROPERTIES)ExAllocatePool2(POOL_FLAG_PAGED,needed,'fMoY');if(properties==NULL)return STATUS_INSUFFICIENT_RESOURCES;status=FltGetVolumeProperties(objects->Volume,properties,needed,&needed);removable=NT_SUCCESS(status)&&((properties->DeviceCharacteristics&FILE_REMOVABLE_MEDIA)!=0);ExFreePoolWithTag(properties,'fMoY');if(!removable)return STATUS_FLT_DO_NOT_ATTACH;status=FltAllocateContext(g_Filter,FLT_INSTANCE_CONTEXT,sizeof(YOMF_INSTANCE_CONTEXT),NonPagedPoolNx,(PFLT_CONTEXT*)&context);if(!NT_SUCCESS(status))return status;RtlZeroMemory(context,sizeof(*context));RtlInitEmptyUnicodeString(&volumeName,context->VolumeName,sizeof(context->VolumeName));status=FltGetVolumeName(objects->Volume,&volumeName,NULL);if(NT_SUCCESS(status))status=FltSetInstanceContext(objects->Instance,FLT_SET_CONTEXT_KEEP_IF_EXISTS,context,NULL);FltReleaseContext(context);return status;}
FLT_PREOP_CALLBACK_STATUS YomfPreOperation(PFLT_CALLBACK_DATA data,PCFLT_RELATED_OBJECTS objects,PVOID* completionContext){PFLT_PORT client=g_ClientPort;UNREFERENCED_PARAMETER(completionContext);if(client!=NULL){YOMF_EVENT event={0};LARGE_INTEGER timeout;PYOMF_INSTANCE_CONTEXT context=NULL;event.Size=sizeof(event);event.AbiVersion=YOMF_EVENT_ABI;event.Sequence=(ULONGLONG)InterlockedIncrement64(&g_Sequence);KeQuerySystemTime(&event.SystemTime100ns);event.ProcessId=FltGetRequestorProcessId(data);event.MajorFunction=data->Iopb->MajorFunction;event.RequestorMode=(UCHAR)data->RequestorMode;event.IrpFlags=data->Iopb->IrpFlags;if(NT_SUCCESS(FltGetInstanceContext(objects->Instance,(PFLT_CONTEXT*)&context))){RtlCopyMemory(event.VolumeName,context->VolumeName,sizeof(event.VolumeName));FltReleaseContext(context);}timeout.QuadPart=0;(VOID)FltSendMessage(g_Filter,&client,&event,sizeof(event),NULL,NULL,&timeout);}/* Detection-only: no ACCESS_DENIED completion in 0.23.0. */return FLT_PREOP_SUCCESS_NO_CALLBACK;}
