using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text.Json;
using YoungOne.MediaControl.Agent.Policy;
namespace YoungOne.MediaControl.Agent.Enforcement;
public static class DriverPolicyPacketBuilder{
 public const uint Magic=0x594F4D43;public const uint AbiVersion=2;public const int HeaderSize=56;public const int RuleSize=64;public const int MaxPayloadBytes=1024*1024;
 const uint HasVendor=1,HasProduct=2,HasSerial=4;
 public static byte[] Build(PolicyEnvelope envelope){using JsonDocument document=JsonDocument.Parse(envelope.PayloadJson);JsonElement root=document.RootElement;if(!root.TryGetProperty("rules",out JsonElement rules)||rules.ValueKind!=JsonValueKind.Array||rules.GetArrayLength()==0)throw new InvalidDataException("Policy contains no rules");int payloadLength=checked(rules.GetArrayLength()*RuleSize);if(payloadLength>MaxPayloadBytes)throw new InvalidDataException("Compiled policy exceeds driver limit");byte[] packet=new byte[HeaderSize+payloadLength];BinaryPrimitives.WriteUInt32LittleEndian(packet.AsSpan(0,4),Magic);BinaryPrimitives.WriteUInt32LittleEndian(packet.AsSpan(4,4),AbiVersion);BinaryPrimitives.WriteUInt64LittleEndian(packet.AsSpan(8,8),checked((ulong)envelope.PolicyVersion));BinaryPrimitives.WriteUInt32LittleEndian(packet.AsSpan(16,4),checked((uint)rules.GetArrayLength()));BinaryPrimitives.WriteUInt32LittleEndian(packet.AsSpan(20,4),checked((uint)payloadLength));int offset=HeaderSize;foreach(JsonElement rule in rules.EnumerateArray()){WriteRule(packet.AsSpan(offset,RuleSize),rule);offset+=RuleSize;}SHA256.HashData(packet.AsSpan(HeaderSize,payloadLength),packet.AsSpan(24,32));return packet;}
 static void WriteRule(Span<byte> output,JsonElement rule){uint flags=0;BinaryPrimitives.WriteUInt32LittleEndian(output[0..4],MediaType(Value(rule,"mediaType")));BinaryPrimitives.WriteUInt32LittleEndian(output[4..8],Action(Value(rule,"readAction")));BinaryPrimitives.WriteUInt32LittleEndian(output[8..12],Action(Value(rule,"writeAction")));BinaryPrimitives.WriteUInt32LittleEndian(output[12..16],Action(Value(rule,"executeAction")));string? vendor=Optional(rule,"vendorId");string? product=Optional(rule,"productId");string? serial=Optional(rule,"serialHash");if(vendor is not null){flags|=HasVendor;BinaryPrimitives.WriteUInt16LittleEndian(output[20..22],ParseHex16(vendor,"vendorId"));}if(product is not null){flags|=HasProduct;BinaryPrimitives.WriteUInt16LittleEndian(output[22..24],ParseHex16(product,"productId"));}if(serial is not null){byte[] hash;try{hash=Convert.FromHexString(serial);}catch(FormatException ex){throw new InvalidDataException("serialHash must be hexadecimal",ex);}if(hash.Length!=32)throw new InvalidDataException("serialHash must contain 32 bytes");flags|=HasSerial;hash.CopyTo(output[24..56]);}BinaryPrimitives.WriteUInt32LittleEndian(output[16..20],flags);BinaryPrimitives.WriteUInt32LittleEndian(output[56..60],Offline(Optional(rule,"offlineBehavior")));long grace=rule.TryGetProperty("offlineGraceSeconds",out JsonElement graceValue)?graceValue.GetInt64():0;if(grace<0||grace>uint.MaxValue)throw new InvalidDataException("offlineGraceSeconds is out of range");BinaryPrimitives.WriteUInt32LittleEndian(output[60..64],(uint)grace);}
 static string Value(JsonElement item,string name)=>item.TryGetProperty(name,out JsonElement value)&&value.ValueKind==JsonValueKind.String?value.GetString()??throw new InvalidDataException(name+" is empty"):throw new InvalidDataException(name+" is required");
 static string? Optional(JsonElement item,string name)=>item.TryGetProperty(name,out JsonElement value)&&value.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(value.GetString())?value.GetString():null;
 static ushort ParseHex16(string value,string name){if(value.Length!=4||!ushort.TryParse(value,System.Globalization.NumberStyles.HexNumber,System.Globalization.CultureInfo.InvariantCulture,out ushort parsed))throw new InvalidDataException(name+" must be four hexadecimal characters");return parsed;}
 static uint MediaType(string value)=>value.ToUpperInvariant() switch{"USB_STORAGE"=>1,"PORTABLE_DEVICE"=>2,"OPTICAL_MEDIA"=>3,"BLUETOOTH"=>4,_=>throw new InvalidDataException("Unsupported driver mediaType: "+value)};
 static uint Action(string value)=>value.ToUpperInvariant() switch{"ALLOW"=>1,"READ_ONLY"=>2,"BLOCK"=>3,"DETECT_ONLY"=>4,_=>throw new InvalidDataException("Unsupported driver action: "+value)};
 static uint Offline(string? value)=>value?.ToUpperInvariant() switch{"LAST_KNOWN"=>1,"FAIL_CLOSED"=>2,"DETECT_ONLY"=>3,null=>1,_=>throw new InvalidDataException("Unsupported offlineBehavior: "+value)};
}
