package com.youngone.mediacontrol.identity.integration;

import org.springframework.stereotype.Component;
import java.nio.charset.StandardCharsets;import java.security.*;import java.time.Instant;import java.util.*;

@Component public class CsvIdentityParser{
 private static final int MAX_ROWS=100_000;
 public ParseResult parse(byte[] bytes){String text=new String(bytes,StandardCharsets.UTF_8);if(text.startsWith("\uFEFF"))text=text.substring(1);List<List<String>>records=records(text);if(records.isEmpty())return new ParseResult(List.of(),List.of("EMPTY_FILE"));Map<String,Integer>header=header(records.getFirst());List<String>errors=new ArrayList<>();for(String required:List.of("externalobjectid","immutablepersonkey","employmentstatus"))if(!header.containsKey(required))errors.add("MISSING_HEADER:"+required);if(!errors.isEmpty())return new ParseResult(List.of(),errors);List<NormalizedIdentity>items=new ArrayList<>();Set<String>externalIds=new HashSet<>();for(int i=1;i<records.size()&&i<=MAX_ROWS;i++){List<String>row=records.get(i);if(row.stream().allMatch(String::isBlank))continue;try{String external=get(row,header,"externalobjectid");String immutable=get(row,header,"immutablepersonkey");if(external.isBlank()||immutable.isBlank())throw new IllegalArgumentException("required identifier is blank");if(!externalIds.add(external))throw new IllegalArgumentException("duplicate externalObjectId in file");EmploymentStatus status=EmploymentStatus.valueOf(get(row,header,"employmentstatus").toUpperCase(Locale.ROOT));String canonical=String.join("|",external,immutable,get(row,header,"employeenumber"),get(row,header,"loginid"),get(row,header,"windowssid"),get(row,header,"upn"),get(row,header,"email"),status.name(),get(row,header,"organizationexternalid"),get(row,header,"sourceversion"));items.add(new NormalizedIdentity(external,immutable,empty(get(row,header,"employeenumber")),empty(get(row,header,"loginid")),empty(get(row,header,"windowssid")),empty(get(row,header,"upn")),empty(get(row,header,"email")),empty(get(row,header,"displayname")),status,empty(get(row,header,"organizationexternalid")),empty(get(row,header,"managerimmutablekey")),groups(get(row,header,"groups")),instant(get(row,header,"effectivefrom")),instant(get(row,header,"effectiveto")),empty(get(row,header,"sourceversion")),sha256(canonical)));}catch(Exception e){errors.add("ROW_"+(i+1)+":"+e.getMessage());}}
 if(records.size()-1>MAX_ROWS)errors.add("ROW_LIMIT_EXCEEDED:"+MAX_ROWS);return new ParseResult(items,List.copyOf(errors));}
 private Map<String,Integer>header(List<String>row){Map<String,Integer>h=new HashMap<>();for(int i=0;i<row.size();i++)h.put(row.get(i).replace("_","").trim().toLowerCase(Locale.ROOT),i);return h;}
 private String get(List<String>row,Map<String,Integer>h,String key){Integer i=h.get(key);return i==null||i>=row.size()?"":row.get(i).trim();}
 private String empty(String v){return v==null||v.isBlank()?null:v;}private Instant instant(String v){return v==null||v.isBlank()?null:Instant.parse(v);}private Set<String>groups(String v){if(v==null||v.isBlank())return Set.of();return Set.copyOf(Arrays.stream(v.split(";")).map(String::trim).filter(x->!x.isBlank()).toList());}
 private String sha256(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private List<List<String>>records(String text){List<List<String>>all=new ArrayList<>();List<String>row=new ArrayList<>();StringBuilder field=new StringBuilder();boolean quoted=false;for(int i=0;i<text.length();i++){char c=text.charAt(i);if(c=='"'){if(quoted&&i+1<text.length()&&text.charAt(i+1)=='"'){field.append('"');i++;}else quoted=!quoted;}else if(c==','&&!quoted){row.add(field.toString());field.setLength(0);}else if((c=='\n'||c=='\r')&&!quoted){if(c=='\r'&&i+1<text.length()&&text.charAt(i+1)=='\n')i++;row.add(field.toString());field.setLength(0);all.add(row);row=new ArrayList<>();}else field.append(c);}if(quoted)throw new IllegalArgumentException("UNCLOSED_QUOTE");if(field.length()>0||!row.isEmpty()){row.add(field.toString());all.add(row);}return all;}
 public record ParseResult(List<NormalizedIdentity> identities,List<String> errors){}
}