package com.youngone.mediacontrol.agent.domain;
import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="agent_uninstall_tokens")
public class AgentUninstallToken{
 @Id private UUID id;@Column(name="agent_id",nullable=false)private UUID agentId;@Column(nullable=false,length=100,unique=true)private String nonce;@Lob @Column(name="payload_json",nullable=false,columnDefinition="LONGTEXT")private String payloadJson;@Column(name="payload_hash",nullable=false,length=64)private String payloadHash;@Lob @Column(nullable=false)private String signature;@Column(name="signing_key_id",nullable=false,length=100)private String signingKeyId;@Column(nullable=false,length=20)private String status;@Column(nullable=false,length=500)private String reason;@Column(name="issued_by",nullable=false,length=150)private String issuedBy;@Column(name="issued_at",nullable=false)private Instant issuedAt;@Column(name="expires_at",nullable=false)private Instant expiresAt;@Column(name="consumed_at")private Instant consumedAt;
 protected AgentUninstallToken(){}
 public AgentUninstallToken(UUID id,UUID agentId,String nonce,String payloadJson,String payloadHash,String signature,String signingKeyId,String reason,String issuedBy,Instant issuedAt,Instant expiresAt){this.id=id;this.agentId=agentId;this.nonce=nonce;this.payloadJson=payloadJson;this.payloadHash=payloadHash;this.signature=signature;this.signingKeyId=signingKeyId;this.reason=reason;this.issuedBy=issuedBy;this.issuedAt=issuedAt;this.expiresAt=expiresAt;status="ISSUED";}
 public UUID getId(){return id;}public UUID getAgentId(){return agentId;}public String getNonce(){return nonce;}public String getPayloadJson(){return payloadJson;}public String getPayloadHash(){return payloadHash;}public String getSignature(){return signature;}public String getSigningKeyId(){return signingKeyId;}public String getStatus(){return status;}public String getReason(){return reason;}public String getIssuedBy(){return issuedBy;}public Instant getIssuedAt(){return issuedAt;}public Instant getExpiresAt(){return expiresAt;}
}
