ALTER TABLE agents ADD COLUMN credential_hash VARCHAR(64) NOT NULL DEFAULT 'MIGRATION_REQUIRES_ROTATION';
ALTER TABLE agent_event_receipts ADD COLUMN payload_hash VARCHAR(64) NOT NULL DEFAULT 'LEGACY';
