ALTER TABLE hr_integration_sources ADD COLUMN created_by VARCHAR(100) NOT NULL DEFAULT 'MIGRATION';
ALTER TABLE hr_sync_runs ADD COLUMN initiated_by VARCHAR(100) NOT NULL DEFAULT 'MIGRATION';
ALTER TABLE hr_sync_runs ADD COLUMN file_hash VARCHAR(64);
ALTER TABLE hr_sync_runs ADD COLUMN dry_run BOOLEAN NOT NULL DEFAULT FALSE;