#pragma once
#include <devioctl.h>
#define YOMC_DEVICE_TYPE 0x8000
#define YOMC_POLICY_MAGIC 0x594F4D43UL
#define YOMC_ABI_VERSION 2UL
#define YOMC_MAX_POLICY_BYTES (1024UL * 1024UL)
#define YOMC_RULE_BYTES 64UL
#define YOMC_SELECTOR_VENDOR 0x1UL
#define YOMC_SELECTOR_PRODUCT 0x2UL
#define YOMC_SELECTOR_SERIAL 0x4UL
#define IOCTL_YOMC_SET_POLICY CTL_CODE(YOMC_DEVICE_TYPE,0x800,METHOD_BUFFERED,FILE_WRITE_DATA)
#define IOCTL_YOMC_QUERY_STATUS CTL_CODE(YOMC_DEVICE_TYPE,0x801,METHOD_BUFFERED,FILE_READ_DATA)
#define IOCTL_YOMC_EVALUATE CTL_CODE(YOMC_DEVICE_TYPE,0x802,METHOD_BUFFERED,FILE_READ_DATA|FILE_WRITE_DATA)
typedef enum _YOMC_ACTION{YomcActionInvalid=0,YomcActionAllow=1,YomcActionReadOnly=2,YomcActionBlock=3,YomcActionDetectOnly=4}YOMC_ACTION;
typedef enum _YOMC_OPERATION{YomcOperationRead=1,YomcOperationWrite=2,YomcOperationExecute=3}YOMC_OPERATION;
#pragma pack(push,1)
typedef struct _YOMC_POLICY_HEADER{ULONG Magic;ULONG AbiVersion;ULONGLONG PolicyVersion;ULONG RuleCount;ULONG PayloadLength;UCHAR PayloadHash[32];}YOMC_POLICY_HEADER,*PYOMC_POLICY_HEADER;
typedef struct _YOMC_POLICY_RULE{ULONG MediaType;ULONG ReadAction;ULONG WriteAction;ULONG ExecuteAction;ULONG SelectorFlags;USHORT VendorId;USHORT ProductId;UCHAR SerialHash[32];ULONG OfflineBehavior;ULONG OfflineGraceSeconds;}YOMC_POLICY_RULE,*PYOMC_POLICY_RULE;
typedef struct _YOMC_EVALUATE_REQUEST{ULONG MediaType;ULONG Operation;USHORT VendorId;USHORT ProductId;UCHAR SerialHash[32];}YOMC_EVALUATE_REQUEST,*PYOMC_EVALUATE_REQUEST;
typedef struct _YOMC_EVALUATE_RESULT{ULONG Action;ULONG Matched;ULONG MatchedRuleIndex;ULONGLONG PolicyVersion;}YOMC_EVALUATE_RESULT,*PYOMC_EVALUATE_RESULT;
typedef struct _YOMC_DRIVER_STATUS{ULONG Magic;ULONG AbiVersion;ULONGLONG AcceptedPolicyVersion;ULONG AcceptedRuleCount;ULONG PolicyLoaded;ULONG EvaluatorReady;ULONG EnforcementReady;NTSTATUS LastPolicyStatus;}YOMC_DRIVER_STATUS,*PYOMC_DRIVER_STATUS;
#pragma pack(pop)
C_ASSERT(sizeof(YOMC_POLICY_HEADER)==56);
C_ASSERT(sizeof(YOMC_POLICY_RULE)==YOMC_RULE_BYTES);
