package com.youngone.mediacontrol.agent.application;
import com.youngone.mediacontrol.agent.api.AgentRequests;import com.youngone.mediacontrol.agent.domain.*;import com.youngone.mediacontrol.agent.infra.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.Instant;import java.util.*;
@Service public class AgentService{
 private final AgentRepository agents;private final AgentEventReceiptRepository receipts;private final AgentIdentityConflictRepository conflicts;private final CredentialService credentials;private final IdentityDecisionService identity;
 public AgentService(AgentRepository a,AgentEventReceiptRepository r,AgentIdentityConflictRepository f,CredentialService c,IdentityDecisionService i){agents=a;receipts=r;conflicts=f;credentials=c;identity=i;}
 @Transactional public Registration register(AgentRequests.Register r,String ip){
  if(!credentials.validBootstrap(r.bootstrapToken()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid bootstrap token");String evidence=effectiveEvidence(r);Instant now=Instant.now();Optional<Agent> sameInstall=agents.findByInstallationId(r.installationId());
  if(sameInstall.isPresent()){Agent a=sameInstall.get();boolean evidenceMatches=Objects.equals(a.getDeviceEvidenceHash(),evidence);IdentityDisposition d=identity.decide(r.environmentType(),true,evidenceMatches,Objects.equals(a.getBootSessionId(),r.bootSessionId()));if(d==IdentityDisposition.DUPLICATE_REJECTED){a.markDuplicateSuspected();conflicts.save(new AgentIdentityConflict(a.getId(),r.installationId(),a.getDeviceEvidenceHash(),evidence,r.bootSessionId(),now));return new Registration(a,null,true);}String key=credentials.issue();a.refreshIdentity(r.bootSessionId(),credentials.hash(key),r.agentVersion(),r.osVersion(),ip,now);return new Registration(a,key,false);}
  boolean evidenceSeen=agents.findFirstByDeviceEvidenceHashAndEnvironmentType(evidence,r.environmentType()).isPresent();IdentityDisposition disposition=identity.decide(r.environmentType(),false,evidenceSeen,false);String key=credentials.issue();Agent a=agents.save(new Agent(UUID.randomUUID(),r.installationId(),r.hostname(),r.agentVersion(),r.osVersion(),ip,credentials.hash(key),r.environmentType(),evidence,r.tpmEkHash(),r.vdiProviderId(),r.organizationDeviceId(),r.bootSessionId(),disposition,now));return new Registration(a,key,false);
 }
 private String effectiveEvidence(AgentRequests.Register r){String value=r.deviceEvidenceHash();if((value==null||value.isBlank())&&r.environmentType()==EnvironmentType.NON_PERSISTENT_VDI)value=r.vdiProviderId();if(value==null||value.isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"deviceEvidenceHash or VDI provider ID is required");return value;}
 @Transactional public HeartbeatResult heartbeat(UUID id,String key,AgentRequests.Heartbeat r,String ip){Agent a=agents.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Agent not found"));if(!a.hasCredentialHash(credentials.hash(key==null?"":key)))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid agent credential");String hash=credentials.hash(r.agentVersion()+"|"+r.osVersion()+"|"+r.queueDepth()+"|"+String.valueOf(r.policyVersion())+"|"+r.controlStatus().name());var existing=receipts.findByAgentIdAndEventId(id,r.eventId());if(existing.isPresent()){if(!existing.get().samePayload(hash))throw new ResponseStatusException(HttpStatus.CONFLICT,"eventId payload mismatch");return new HeartbeatResult(a,true);}a.heartbeat(r.agentVersion(),r.osVersion(),ip,r.controlStatus(),Instant.now());receipts.save(new AgentEventReceipt(id,r.eventId(),hash,Instant.now()));return new HeartbeatResult(a,false);}
 @Transactional(readOnly=true) public Agent authenticate(UUID id,String key){Agent a=agents.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Agent not found"));if(!a.hasCredentialHash(credentials.hash(key==null?"":key)))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid agent credential");if(a.getSecurityStatus()==SecurityStatus.REVOKED)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Agent revoked");return a;}
 public record Registration(Agent agent,String key,boolean conflict){}public record HeartbeatResult(Agent agent,boolean duplicate){}
}
