package com.youngone.mediacontrol.agent.application;
import com.youngone.mediacontrol.agent.api.AgentUninstallModels;import com.youngone.mediacontrol.agent.domain.*;import com.youngone.mediacontrol.agent.infra.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import tools.jackson.databind.ObjectMapper;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.Instant;import java.time.temporal.ChronoUnit;import java.util.*;
@Service public class AgentUninstallService{
 private final AgentRepository agents;private final AgentUninstallTokenRepository tokens;private final UninstallSigningService signing;private final ObjectMapper json;
 public AgentUninstallService(AgentRepository agents,AgentUninstallTokenRepository tokens,UninstallSigningService signing,ObjectMapper json){this.agents=agents;this.tokens=tokens;this.signing=signing;this.json=json;}
 @Transactional public AgentUninstallModels.IssueResponse issue(UUID agentId,AgentUninstallModels.IssueRequest request,String actor){Agent agent=agents.findById(agentId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Agent not found"));Instant issuedAt=Instant.now();Instant expiresAt=issuedAt.plus(request.validMinutes(),ChronoUnit.MINUTES);String nonce=UUID.randomUUID().toString().replace("-","");var payload=new AgentUninstallModels.TokenPayload(1,agentId,agent.getInstallationId(),nonce,issuedAt,expiresAt,request.reason(),actor);String payloadJson=json.writeValueAsString(payload);String hash=sha256(payloadJson);String signature=signing.sign(payloadJson);AgentUninstallToken token=tokens.save(new AgentUninstallToken(UUID.randomUUID(),agentId,nonce,payloadJson,hash,signature,signing.keyId(),request.reason(),actor,issuedAt,expiresAt));var envelope=new AgentUninstallModels.TokenEnvelope(payloadJson,hash,signature,signing.keyId());return new AgentUninstallModels.IssueResponse(token.getId(),agentId,agent.getInstallationId(),issuedAt,expiresAt,token.getStatus(),envelope);}
 public String pinnedPublicKey(){return signing.rawPublicKey();}public boolean usesEphemeralKey(){return signing.isEphemeral();}
 private static String sha256(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
