using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;
using Xunit;
using YoungOne.MediaControl.Agent.Enforcement;
using YoungOne.MediaControl.Agent.Policy;
namespace YoungOne.MediaControl.Agent.Tests;
public sealed class DriverPolicyPacketBuilderTests{
 [Fact]public void BuildsAbiV2HeaderAndCompiledRule(){string json="""{"schemaVersion":2,"policyVersion":7,"rules":[{"mediaType":"USB_STORAGE","vendorId":"1234","productId":"ABCD","serialHash":"000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f","readAction":"ALLOW","writeAction":"READ_ONLY","executeAction":"BLOCK","offlineBehavior":"LAST_KNOWN","offlineGraceSeconds":300}],"effectiveAt":"2026-09-05T00:00:00Z"}""";byte[] packet=DriverPolicyPacketBuilder.Build(Envelope(json,7));Assert.Equal(DriverPolicyPacketBuilder.Magic,BinaryPrimitives.ReadUInt32LittleEndian(packet.AsSpan(0,4)));Assert.Equal(2u,BinaryPrimitives.ReadUInt32LittleEndian(packet.AsSpan(4,4)));Assert.Equal(7ul,BinaryPrimitives.ReadUInt64LittleEndian(packet.AsSpan(8,8)));Assert.Equal(1u,BinaryPrimitives.ReadUInt32LittleEndian(packet.AsSpan(16,4)));Assert.Equal(64u,BinaryPrimitives.ReadUInt32LittleEndian(packet.AsSpan(20,4)));Assert.Equal(SHA256.HashData(packet.AsSpan(DriverPolicyPacketBuilder.HeaderSize)),packet.AsSpan(24,32).ToArray());int o=DriverPolicyPacketBuilder.HeaderSize;Assert.Equal(1u,BinaryPrimitives.ReadUInt32LittleEndian(packet.AsSpan(o,4)));Assert.Equal(1u,BinaryPrimitives.ReadUInt32LittleEndian(packet.AsSpan(o+4,4)));Assert.Equal(2u,BinaryPrimitives.ReadUInt32LittleEndian(packet.AsSpan(o+8,4)));Assert.Equal(3u,BinaryPrimitives.ReadUInt32LittleEndian(packet.AsSpan(o+12,4)));Assert.Equal(7u,BinaryPrimitives.ReadUInt32LittleEndian(packet.AsSpan(o+16,4)));Assert.Equal(0x1234,BinaryPrimitives.ReadUInt16LittleEndian(packet.AsSpan(o+20,2)));Assert.Equal(0xABCD,BinaryPrimitives.ReadUInt16LittleEndian(packet.AsSpan(o+22,2)));Assert.Equal(300u,BinaryPrimitives.ReadUInt32LittleEndian(packet.AsSpan(o+60,4)));}
 [Fact]public void RejectsPolicyWithoutRules(){string json="""{"schemaVersion":2,"policyVersion":1,"rules":[]}""";Assert.Throws<InvalidDataException>(()=>DriverPolicyPacketBuilder.Build(Envelope(json,1)));}
 [Fact]public void RejectsMalformedSelector(){string json="""{"schemaVersion":2,"policyVersion":1,"rules":[{"mediaType":"USB_STORAGE","vendorId":"XYZ","readAction":"ALLOW","writeAction":"BLOCK","executeAction":"BLOCK"}]}""";Assert.Throws<InvalidDataException>(()=>DriverPolicyPacketBuilder.Build(Envelope(json,1)));}
 [Fact]public void RejectsUnsupportedMediaType(){string json="""{"schemaVersion":2,"policyVersion":1,"rules":[{"mediaType":"UNKNOWN","readAction":"ALLOW","writeAction":"BLOCK","executeAction":"BLOCK"}]}""";Assert.Throws<InvalidDataException>(()=>DriverPolicyPacketBuilder.Build(Envelope(json,1)));}
 static PolicyEnvelope Envelope(string json,long version){string hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(json))).ToLowerInvariant();return new(Guid.NewGuid(),version,json,hash,Convert.ToBase64String(new byte[64]),"test",Convert.ToBase64String(new byte[32]),DateTimeOffset.UtcNow,null);}
}
