using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;
using YoungOne.MediaControl.Agent.Policy;
namespace YoungOne.MediaControl.Agent.Detection;
public sealed class KernelMinifilterEventSource(VolumeDeviceResolver resolver,ILogger<KernelMinifilterEventSource> logger):IMediaEventSource{
 const string PortName="\\YoungOneMediaFilterPort";const int MessageBytes=256;
 readonly KernelEventRateGate rateGate=new(TimeSpan.FromSeconds(1));
 public async IAsyncEnumerable<DetectedMedia> WatchAsync([System.Runtime.CompilerServices.EnumeratorCancellation]CancellationToken ct){while(!ct.IsCancellationRequested){int hr=FilterConnectCommunicationPort(PortName,0,IntPtr.Zero,0,IntPtr.Zero,out var handle);if(hr!=0){logger.LogDebug("Minifilter event port unavailable: 0x{HResult:X8}",hr);await Task.Delay(TimeSpan.FromSeconds(5),ct);continue;}using(handle)using(ct.Register(handle.Dispose)){logger.LogInformation("Connected to minifilter detection port");while(!ct.IsCancellationRequested){IntPtr buffer=Marshal.AllocHGlobal(MessageBytes);try{int result=await Task.Run(()=>FilterGetMessage(handle,buffer,MessageBytes,IntPtr.Zero),CancellationToken.None);if(result!=0)break;var message=Marshal.PtrToStructure<FilterMessage>(buffer);if(message.Event.Size!=Marshal.SizeOf<KernelEvent>()||message.Event.AbiVersion!=2)continue;MediaOperation? operation=Map(message.Event.MajorFunction);if(operation is null||!rateGate.ShouldEmit(message.Event.VolumeName,message.Event.ProcessId,message.Event.MajorFunction,DateTimeOffset.UtcNow))continue;MediaDeviceIdentity? device=resolver.Resolve(message.Event.VolumeName);if(device is null){logger.LogWarning("Unresolved removable volume {Volume}; event remains detect-only",message.Event.VolumeName);yield return new DetectedMedia("REMOVABLE_STORAGE",null,null,null,$"UNRESOLVED_VOLUME:{message.Event.VolumeName}",operation.Value,null);}else yield return new DetectedMedia(device.MediaType,device.VendorId,device.ProductId,device.SerialHash,device.DeviceInstanceId,operation.Value,null);}finally{Marshal.FreeHGlobal(buffer);}}}}}
 public static MediaOperation? Map(byte major)=>major switch{0=>MediaOperation.Open,2=>MediaOperation.Read,3=>MediaOperation.Write,6=>MediaOperation.Write,255=>MediaOperation.Execute,_=>null};
 public static int EventSize=>Marshal.SizeOf<KernelEvent>();
 [StructLayout(LayoutKind.Sequential)]struct FilterMessage{public uint ReplyLength;public ulong MessageId;public KernelEvent Event;}
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]struct KernelEvent{public uint Size;public uint AbiVersion;public ulong Sequence;public long SystemTime100ns;public uint ProcessId;public byte MajorFunction;public byte RequestorMode;public ushort Reserved;public uint IrpFlags;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=64)]public string VolumeName;}
 [DllImport("fltlib.dll",CharSet=CharSet.Unicode)]static extern int FilterConnectCommunicationPort(string portName,uint options,IntPtr context,uint contextSize,IntPtr securityAttributes,out SafeFileHandle portHandle);
 [DllImport("fltlib.dll")]static extern int FilterGetMessage(SafeFileHandle portHandle,IntPtr messageBuffer,uint messageBufferSize,IntPtr overlapped);
}
