using System.Management;
using System.Runtime.InteropServices;
namespace YoungOne.MediaControl.Agent.Detection;
public sealed class VolumeDeviceResolver(ILogger<VolumeDeviceResolver> logger){
 readonly object gate=new();DateTimeOffset expires=DateTimeOffset.MinValue;Dictionary<string,MediaDeviceIdentity> cache=new(StringComparer.OrdinalIgnoreCase);
 public MediaDeviceIdentity? Resolve(string? kernelVolumeName){if(string.IsNullOrWhiteSpace(kernelVolumeName))return null;lock(gate){if(DateTimeOffset.UtcNow>=expires)Refresh();return cache.GetValueOrDefault(kernelVolumeName.TrimEnd('\0'));}}
 void Refresh(){var next=new Dictionary<string,MediaDeviceIdentity>(StringComparer.OrdinalIgnoreCase);try{using var logical=new ManagementObjectSearcher("SELECT DeviceID FROM Win32_LogicalDisk WHERE DriveType=2");foreach(ManagementObject row in logical.Get()){using(row){string? drive=row["DeviceID"]?.ToString();if(string.IsNullOrWhiteSpace(drive))continue;string? kernel=QueryTarget(drive);MediaDeviceIdentity? device=FindDevice(drive);if(kernel is not null&&device is not null)next[kernel]=device;}}}catch(ManagementException ex){logger.LogWarning(ex,"Removable volume to PnP refresh failed");}cache=next;expires=DateTimeOffset.UtcNow.AddSeconds(10);}
 static MediaDeviceIdentity? FindDevice(string drive){string escaped=drive.Replace("'","''",StringComparison.Ordinal);using var partitions=new ManagementObjectSearcher($"ASSOCIATORS OF {{Win32_LogicalDisk.DeviceID='{escaped}'}} WHERE AssocClass=Win32_LogicalDiskToPartition");foreach(ManagementObject partition in partitions.Get()){using(partition){string? partitionId=partition["DeviceID"]?.ToString();if(string.IsNullOrWhiteSpace(partitionId))continue;string p=partitionId.Replace("'","''",StringComparison.Ordinal);using var disks=new ManagementObjectSearcher($"ASSOCIATORS OF {{Win32_DiskPartition.DeviceID='{p}'}} WHERE AssocClass=Win32_DiskDriveToDiskPartition");foreach(ManagementObject disk in disks.Get()){using(disk){string? id=disk["PNPDeviceID"]?.ToString();if(string.IsNullOrWhiteSpace(id))continue;var storage=MediaDeviceNormalizer.Normalize(id,"DiskDrive",disk["Model"]?.ToString(),disk["SerialNumber"]?.ToString());return AddUsbVidPid(storage);}}}}return null;}
 static MediaDeviceIdentity AddUsbVidPid(MediaDeviceIdentity storage){if(storage.VendorId is not null||storage.SerialHash is null)return storage;using var pnp=new ManagementObjectSearcher("SELECT PNPDeviceID,Name FROM Win32_PnPEntity WHERE PNPDeviceID LIKE 'USB%'");foreach(ManagementObject row in pnp.Get()){using(row){string? id=row["PNPDeviceID"]?.ToString();if(string.IsNullOrWhiteSpace(id))continue;var usb=MediaDeviceNormalizer.Normalize(id,"USB",row["Name"]?.ToString());if(usb.SerialHash==storage.SerialHash&&usb.VendorId is not null)return storage with{VendorId=usb.VendorId,ProductId=usb.ProductId};}}return storage;}
 static string? QueryTarget(string drive){var buffer=new char[1024];uint count=QueryDosDevice(drive,buffer,buffer.Length);return count==0?null:new string(buffer,0,(int)count).Split('\0',StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();}
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern uint QueryDosDevice(string deviceName,[Out]char[] targetPath,int max);
}
