using System.Management;
using Microsoft.Extensions.Options;
using YoungOne.MediaControl.Agent.Policy;
namespace YoungOne.MediaControl.Agent.Detection;
public sealed class WindowsMediaEventSource(IOptions<AgentOptions> options,ILogger<WindowsMediaEventSource> logger):IMediaEventSource{
 public async IAsyncEnumerable<DetectedMedia> WatchAsync([System.Runtime.CompilerServices.EnumeratorCancellation]CancellationToken ct){
  var previous=new Dictionary<string,MediaDeviceIdentity>(StringComparer.OrdinalIgnoreCase);using var timer=new PeriodicTimer(TimeSpan.FromSeconds(options.Value.DeviceScanSeconds));
  do{Dictionary<string,MediaDeviceIdentity> current=Discover();foreach(var item in current.Values.Where(x=>!previous.ContainsKey(x.DeviceInstanceId))){logger.LogInformation("Media connected: {MediaType} {Device}",item.MediaType,item.DeviceInstanceId);yield return ToEvent(item,MediaOperation.Connect);}foreach(var item in previous.Values.Where(x=>!current.ContainsKey(x.DeviceInstanceId))){logger.LogInformation("Media removed: {MediaType} {Device}",item.MediaType,item.DeviceInstanceId);yield return ToEvent(item,MediaOperation.Eject);}previous=current;}while(await timer.WaitForNextTickAsync(ct));}
 Dictionary<string,MediaDeviceIdentity> Discover(){var result=new Dictionary<string,MediaDeviceIdentity>(StringComparer.OrdinalIgnoreCase);try{using var disks=new ManagementObjectSearcher("SELECT PNPDeviceID,SerialNumber,Model,InterfaceType FROM Win32_DiskDrive WHERE InterfaceType='USB'");foreach(ManagementObject row in disks.Get()){using(row){Add(result,row["PNPDeviceID"]?.ToString(),"DiskDrive",row["Model"]?.ToString(),row["SerialNumber"]?.ToString());}}using var pnp=new ManagementObjectSearcher("SELECT PNPDeviceID,PNPClass,Name FROM Win32_PnPEntity WHERE PNPDeviceID LIKE 'USB%' OR PNPDeviceID LIKE 'SWD\\\\WPDBUSENUM%'");foreach(ManagementObject row in pnp.Get()){using(row){Add(result,row["PNPDeviceID"]?.ToString(),row["PNPClass"]?.ToString(),row["Name"]?.ToString(),null);}}}catch(ManagementException ex){logger.LogError(ex,"Windows media inventory query failed");}return result;}
 static void Add(Dictionary<string,MediaDeviceIdentity> result,string? id,string? pnpClass,string? name,string? serial){if(string.IsNullOrWhiteSpace(id))return;MediaDeviceIdentity device=MediaDeviceNormalizer.Normalize(id,pnpClass,name,serial);if(device.MediaType=="USB_DEVICE")return;result[device.DeviceInstanceId]=device;}
 static DetectedMedia ToEvent(MediaDeviceIdentity d,MediaOperation operation)=>new(d.MediaType,d.VendorId,d.ProductId,d.SerialHash,d.DeviceInstanceId,operation,CurrentUser());
 static string? CurrentUser(){try{using var searcher=new ManagementObjectSearcher("SELECT UserName FROM Win32_ComputerSystem");foreach(ManagementObject row in searcher.Get()){using(row){string? user=row["UserName"]?.ToString();if(!string.IsNullOrWhiteSpace(user))return user;}}}catch(ManagementException){return null;}return null;}
}