package com.youngone.mediacontrol.policy.application;
import com.youngone.mediacontrol.policy.api.PolicyModels;import com.youngone.mediacontrol.policy.domain.*;import com.youngone.mediacontrol.policy.infra.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import tools.jackson.databind.ObjectMapper;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.security.NoSuchAlgorithmException;import java.time.Instant;import java.util.*;
@Service public class PolicyService{
 private final PolicyRepository policies;private final PolicyAssignmentRepository assignments;private final PolicyDeploymentRepository deployments;private final PolicySigningService signing;private final ObjectMapper json;
 public PolicyService(PolicyRepository p,PolicyAssignmentRepository a,PolicyDeploymentRepository d,PolicySigningService s,ObjectMapper j){policies=p;assignments=a;deployments=d;signing=s;json=j;}
 @Transactional public Policy create(PolicyModels.Create r,String actor){validate(r);long version=policies.findFirstByOrderByVersionDesc().map(p->p.getVersion()+1).orElse(1L);var rules=r.rules().stream().sorted(Comparator.comparing(PolicyModels.Rule::selectorKey)).toList();var payload=new PolicyModels.Payload(2,version,rules,r.effectiveAt(),r.expiresAt());String payloadJson=json.writeValueAsString(payload),hash=sha256(payloadJson),signature=signing.sign(payloadJson);return policies.save(new Policy(UUID.randomUUID(),r.name(),version,payloadJson,hash,signature,signing.keyId(),r.effectiveAt(),r.expiresAt(),actor,Instant.now()));}
 @Transactional public Policy approve(UUID id,String actor){Policy p=get(id);try{p.approve(actor,Instant.now());return p;}catch(IllegalArgumentException|IllegalStateException e){throw new ResponseStatusException(HttpStatus.CONFLICT,e.getMessage());}}
 @Transactional public PolicyAssignment assign(PolicyModels.AssignmentCreate r,String actor){Policy p=get(r.policyId());if(p.getStatus()==PolicyStatus.DRAFT)throw new ResponseStatusException(HttpStatus.CONFLICT,"Policy must be approved before assignment");if(r.targetType()==AssignmentTargetType.GLOBAL&&r.targetId()!=null&&!r.targetId().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"GLOBAL targetId must be empty");if(r.targetType()!=AssignmentTargetType.GLOBAL&&(r.targetId()==null||r.targetId().isBlank()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"targetId is required");return assignments.save(new PolicyAssignment(UUID.randomUUID(),r.policyId(),r.targetType(),r.targetId(),r.priority(),actor,Instant.now()));}
 @Transactional public PolicyDeployment deploy(PolicyModels.DeploymentCreate r,String actor){Policy target=get(r.policyId());if(target.getStatus()!=PolicyStatus.APPROVED)throw new ResponseStatusException(HttpStatus.CONFLICT,"Only approved policy can deploy");Policy previous=policies.findFirstByStatusOrderByVersionDesc(PolicyStatus.ACTIVE).orElse(null);if(previous!=null)previous.retire();target.activate();return deployments.save(new PolicyDeployment(UUID.randomUUID(),target.getId(),previous==null?null:previous.getId(),r.rolloutPercentage(),actor,Instant.now()));}
 @Transactional public PolicyDeployment rollback(UUID deploymentId){PolicyDeployment d=deployments.findById(deploymentId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Deployment not found"));Policy current=get(d.getPolicyId());current.retire();if(d.getPreviousPolicyId()!=null){Policy previous=get(d.getPreviousPolicyId());if(previous.getStatus()==PolicyStatus.RETIRED){previous.restoreFromRollback();}}d.rollback();return d;}
 @Transactional(readOnly=true)public PolicyModels.Envelope resolveForAgent(UUID agentId){List<PolicyAssignment> candidates=new ArrayList<>(assignments.findByEnabledTrueAndTargetTypeAndTargetId(AssignmentTargetType.AGENT,agentId.toString()));candidates.addAll(assignments.findByEnabledTrueAndTargetType(AssignmentTargetType.GLOBAL));Policy selected=candidates.stream().sorted(Comparator.comparingInt(PolicyAssignment::getPriority).reversed()).map(a->policies.findById(a.getPolicyId()).orElse(null)).filter(Objects::nonNull).findFirst().orElseGet(()->policies.findFirstByStatusOrderByVersionDesc(PolicyStatus.ACTIVE).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"No policy assigned")));var deployment=deployments.findFirstByStatusInOrderByStartedAtDesc(List.of(DeploymentStatus.RUNNING,DeploymentStatus.COMPLETED));if(deployment.isPresent()&&deployment.get().getPolicyId().equals(selected.getId())&&!deployment.get().includes(agentId)&&deployment.get().getPreviousPolicyId()!=null)selected=get(deployment.get().getPreviousPolicyId());return envelope(selected);}
 public PolicyModels.Envelope envelope(Policy p){return new PolicyModels.Envelope(p.getId(),p.getVersion(),p.getPayloadJson(),p.getPayloadHash(),p.getSignature(),p.getSigningKeyId(),signing.publicKey(),p.getEffectiveAt(),p.getExpiresAt());}private Policy get(UUID id){return policies.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Policy not found"));}
 private void validate(PolicyModels.Create r){if(r.expiresAt()!=null&&!r.expiresAt().isAfter(r.effectiveAt()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"expiresAt must be after effectiveAt");Set<String> seen=new HashSet<>();for(var rule:r.rules())if(!seen.add(rule.selectorKey()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Duplicate media selector: "+rule.selectorKey());}
 private String sha256(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
