package com.youngone.mediacontrol.policy.application;
import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import java.nio.charset.StandardCharsets;import java.security.*;import java.security.spec.*;import java.util.*;
@Service public class PolicySigningService{
 private final PrivateKey privateKey;private final PublicKey publicKey;private final String keyId;
 public PolicySigningService(@Value("${youngone.policy.signing-private-key:}")String encodedPrivate,@Value("${youngone.policy.signing-public-key:}")String encodedPublic,@Value("${youngone.policy.signing-key-id:dev-ephemeral}")String keyId){try{if(encodedPrivate==null||encodedPrivate.isBlank()){KeyPairGenerator g=KeyPairGenerator.getInstance("Ed25519");KeyPair p=g.generateKeyPair();privateKey=p.getPrivate();publicKey=p.getPublic();}else{if(encodedPublic==null||encodedPublic.isBlank())throw new IllegalStateException("Public key is required with configured private key");KeyFactory f=KeyFactory.getInstance("Ed25519");privateKey=f.generatePrivate(new PKCS8EncodedKeySpec(Base64.getDecoder().decode(encodedPrivate)));publicKey=f.generatePublic(new X509EncodedKeySpec(Base64.getDecoder().decode(encodedPublic)));}this.keyId=keyId;}catch(GeneralSecurityException e){throw new IllegalStateException("Invalid Ed25519 signing key",e);}}
 public String sign(String payload){try{Signature s=Signature.getInstance("Ed25519");s.initSign(privateKey);s.update(payload.getBytes(StandardCharsets.UTF_8));return Base64.getEncoder().encodeToString(s.sign());}catch(GeneralSecurityException e){throw new IllegalStateException(e);}}
 public boolean verify(String payload,String signature){try{Signature s=Signature.getInstance("Ed25519");s.initVerify(publicKey);s.update(payload.getBytes(StandardCharsets.UTF_8));return s.verify(Base64.getDecoder().decode(signature));}catch(GeneralSecurityException|IllegalArgumentException e){return false;}}
 public String publicKey(){return Base64.getEncoder().encodeToString(publicKey.getEncoded());}public String keyId(){return keyId;}
}
